### ISSUE TITLE
termy-server crashes with forced-commands when you try to login with ssh client instead of termy-qt

### ISSUE THREAD

**Issue by doverride** [TermySequence/termysequence#1]
I wanted to allow termy-qt logins only. So i tried to add "command=/usr/bin/termy-server" to users authorized_keys. This seems to work fine for termy-qt, but if i try to login with a normal ssh client then it rashes termy-server:

```
Process 14844 (termy-server) of user 10000 dumped core.
       
       Stack trace of thread 14848:
       #0  0x00007f1923ca000b raise (libc.so.6)
       #1  0x00007f1923c8a591 abort (libc.so.6)
       #2  0x000055b410ce61b0 _ZN3Tsq17ProtocolExceptionC1Ei (termy-server)
       #3  0x000055b410d33226 _ZN13ServerMachine8connReadEPKcm (termy-server)
       #4  0x000055b410d3342d _ZN13ServerMachine8connReadEi (termy-server)
       #5  0x000055b410d2b30b _ZN10TermReader8handleFdEv (termy-server)
       #6  0x000055b410d3ccbd _ZN10ThreadBase17runDescriptorLoopEv (termy-server)
       #7  0x000055b410d2b4e4 _ZN10TermReader10threadMainEv (termy-server)
       #8  0x000055b410d3ca0b threadTrampoline (termy-server)
       #9  0x00007f192402f644 start_thread (libpthread.so.0)
       #10 0x00007f1923d62f8f __clone (libc.so.6)

       Stack trace of thread 14846:
       #0  0x00007f1924039944 wait (libpthread.so.0)
       #1  0x000055b410d41048 _ZN10TermReaper8lockLoopEv (termy-server)
       #2  0x000055b410d41115 _ZN10TermReaper10threadMainEv (termy-server)
       #3  0x000055b410d3ca0b threadTrampoline (termy-server)
       #4  0x00007f192402f644 start_thread (libpthread.so.0)
       #5  0x00007f1923d62f8f __clone (libc.so.6)
       
       Stack trace of thread 14844:
       #0  0x00007f1923d584c9 __poll (libc.so.6)
       #1  0x000055b410d3d064 _ZN10ThreadBase22runDescriptorLoopMultiEv (termy-s>
       #2  0x000055b410d181e7 _ZN12TermListener10threadMainEv (termy-server)
       #3  0x000055b410d3cb4e _ZN10ThreadBase3runEi (termy-server)
       #4  0x000055b410ced89b _ZL11runListenerii (termy-server)
       #5  0x000055b410cede5c _Z9runServerv (termy-server)
       #6  0x000055b410ce6711 main (termy-server)
       #7  0x00007f1923c8c1bb __libc_start_main (libc.so.6)
       #8  0x000055b410ce81ea _start (termy-server)

       Stack trace of thread 14847:
       #0  0x00007f1923d584c9 __poll (libc.so.6)
       #1  0x000055b410d3cbfc _ZN10ThreadBase17runDescriptorLoopEv (termy-server)
       #2  0x000055b410d1f105 _ZN11TermMonitor10threadMainEv (termy-server)
       #3  0x000055b410d3ca0b threadTrampoline (termy-server)
       #4  0x00007f192402f644 start_thread (libpthread.so.0)
       #5  0x00007f1923d62f8f __clone (libc.so.6)
```

**Comment by doverride** [comment]
In other words: I am able to crash termy-server with `ssh user@home 'termy-server'`

**Comment by doverride** [comment]
BTW that is from a xterm. instead of a termy-qt term. When i run that command from a termy-qt term then i get a nice message with various options

**Comment by sigalrm** [comment]
Try termy-server-1.0.2-2 from COPR.

This is an abort that should only happen in Debug mode. NDEBUG wasn't getting set in the RPM build. Setting CMAKE_BUILD_TYPE=Release in the spec file fixes it, but this needs more work in the upstream CMakeLists.txt files since setting the build type to "None" or "" seems to be the rule in packaging systems.

**Comment by doverride** [comment]
Will try , thanks, awesome app btw

**Comment by doverride** [comment]
The above issue is resolved.

However termy-qt crashed if I run `shutdown -r now` in a shell on a remote termy-server
steps to reproduce:

open termy-qt, connect to remote termy-server, from a shell on remote termy-server, shutdown the remote system with shutdown -h now.

**Comment by sigalrm** [comment]
I think this is the same issue and it should be fixed in termy-qt-1.0.2-2 from COPR. The abort in this case is caused by the "System going down now!" message that gets printed into the terminal.

**Comment by doverride** [comment]
Could be. I suppose i should see if i can reproduce.

I noticed that qtermy-qt is steadily at the top of my list of cpu hogs with %2.5 cpu. topping firefox and emacs. It is not excessive and i suppose it can be explained by for example the constant generating of thumbnails (and i noticed it does JIT) but still wondering if there would be optimization possible there.

**Comment by doverride** [comment]
Confirmed that the termy-qt crash is also fixed. I think i should close this.
