### ISSUE TITLE
qtermy segfaults if when you close a pane

### ISSUE THREAD

**Issue by doverride** [TermySequence/termysequence#2]
`Jun 04 17:30:13 julius kernel: qtermy[8500]: segfault at 55c694c88270 ip 000055c694c88270 sp 00007ffdca3b33d8 error 15`

I had more than a single pane (one vertical and one horizontal) when i tried to remove the panes with view -> split view -> close pane, qtermy segfaulted.

"Close other panes" had the desired effect for me since i wanted to remove all extra panes

**Comment by sigalrm** [comment]
I have reproduced the crash, thanks

**Comment by doverride** [comment]
Thanks, not sure if i am doing anything wrong or if my expections are wrong but when i select multiline, ctrl shift c  for copy, and the ctrl shift insert/ctrl shift v for paste, then it pastes everything on a single line instead of multi-line

**Comment by sigalrm** [comment]
The split view crash should be fixed in termy-qt 1.0.3-1 in COPR.

For the multiline paste, are you pasting to a shell prompt? If so, do you have Bracketed Paste Mode enabled? (BPM in the status bar). With BPM enabled, bash does not treat newlines in pasted text as Return presses.

**Comment by doverride** [comment]
On Tue, Jun 05, 2018 at 09:52:43AM +0000, sigalrm wrote:
> The split view crash should be fixed in termy-qt 1.0.3-1 in COPR.
> 
> For the multiline paste, are you pasting to a shell prompt? If so, do you have Bracketed Paste Mode enabled? (BPM in the status bar). With BPM enabled, bash does not treat newlines in pasted text as Return presses.

Thanks, Yes looks like , for some reason, BPM is enabled. Not sure why that would be enabled by default

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/TermySequence/termysequence/issues/2#issuecomment-394650974

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift

**Comment by sigalrm** [comment]
It could be enabled in ~/.inputrc. Or, killing vim/emacs can leave the terminal in BPM (exiting the editor normally should not do this).

**Comment by doverride** [comment]
Thanks. This issue is fixed. Closing
