### ISSUE TITLE
how to disable ip address display in terminals?

### ISSUE THREAD

**Issue by doverride** [TermySequence/termysequence#4]
Termy-qt is constantly eating approx. 50% of my CPU because it keeps scrolling long ip6 addresses up and down all the time (these addresses are so long that they dont fit the screen)

Is there a a box to tick to disable this functionality?

**Comment by doverride** [comment]
example

https://tfirg.undo.it/~kcinimod/stuff/image.png

**Comment by sigalrm** [comment]
Global Settings->Effects->Enable badge text scrolling

**Comment by sigalrm** [comment]
I'm looking at the rendering code to try and reduce the CPU usage by only redrawing parts of the window.

**Comment by doverride** [comment]
Thanks, that works!

**Comment by doverride** [comment]
On Thu, Oct 18, 2018 at 01:22:11AM -0700, sigalrm wrote:
> If you want to disable the badge text entirely, you can clear out the string under Profile Settings->Appearance->Format of terminal badge text

I would very much like to have brief chat with you. Can we meet on IRC some time? My nick on Freenode is "grift" 

> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/TermySequence/termysequence/issues/4#issuecomment-430919532

-- 
Key fingerprint = 5F4D 3CDB D3F8 3652 FBD8  02D5 3B6C 5F1D 2C7B 6B02
https://sks-keyservers.net/pks/lookup?op=get&search=0x3B6C5F1D2C7B6B02
Dominick Grift
