### ISSUE TITLE
What set of options will allow Middle click copy/paste out of Termy?

### ISSUE THREAD

**Issue by karcaw** [TermySequence/termysequence#5]
I Use the middle click in my Linux environment all day, is there a set of options I can Set so that I can quickly copy and paste text out of qtermy?  I can select/paste into qtermy, but select/paste out of qtermy does not work.

**Comment by sigalrm** [comment]
Hello, in my Fedora desktop I am able to select text in qtermy and paste it into gedit with middle click. Is this what you want to do?

**Comment by sigalrm** [comment]
Perhaps this is a Wayland issue: https://bugs.kde.org/show_bug.cgi?id=373907. I need to set up a pure Wayland desktop running to test (all of mine are either Xorg or Xwayland).

**Comment by karcaw** [comment]
I'm looking at this again, and it seems that if I click-drag to make a selection, I can paste it with middle click.  but if I double click to select one thing, that does not paste with middle click, instead, I get the last selection I made

**Comment by sigalrm** [comment]
Updated packages are now available in copr and obs. Updates are submitted for F28+.
