### ISSUE TITLE
Case sensitivity issue with files tool

### ISSUE THREAD

**Issue by genrtul** [TermySequence/termysequence#6]
I'm using version 1.1.4 from the Fedora 28 repos. When I try to download files with the files tool I get an error popup "The file's host 'max' does not match the terminal's host 'MAX'". The correct hostname is the upcased version, as reported by the "hostname" command. The issue persists on all hosts I control (they all have upcased names)

**Comment by sigalrm** [comment]
Thanks for this report. I'll make the comparison case-insensitive. The [QUrl.host()](https://doc.qt.io/qt-5.11/qurl.html#host) getter is returning a lowercase name which appears to the cause of this issue.

**Comment by sigalrm** [comment]
A patched qtermy package is now available in [COPR](https://copr.fedorainfracloud.org/coprs/ewalsh/termysequence/) for testing.

**Comment by genrtul** [comment]
The issue is resolved in the patched version

**Comment by sigalrm** [comment]
Updated packages are now available for [Ubuntu](https://termysequence.io/releases/#ubuntu), [OpenSUSE](https://termysequence.io/releases/#opensuse), and [Arch](https://termysequence.io/releases/#arch). Updates submitted for F28+.

**Comment by sigalrm** [comment]
Fedora update is in stable and will be available once it hits the mirrors.
